# -*- coding: utf-8 -*-
"""asn2_part1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BJ29DcXgZlh_YWpGOQOcpBvHxIuX5Du8
"""

import pandas as pd
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import numpy as np

df = pd.read_csv('traindata.csv', index_col = False)
train_df, test_df = train_test_split(df,test_size = 0.1,random_state = 0)
df.head(5)
test_df.to_csv('asn2_testdata.csv', index=False)  
train_df.to_csv('asn2_traindata.csv', index=False)

