# -*- coding: utf-8 -*-
"""asn2_part2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SdHx8_zPpnT05hJXDp55kJ0Aoo1bb327
"""

import pandas as pd
import numpy as np

test_data = pd.read_csv('asn2_testdata.csv', index_col = False)
train_data = pd.read_csv('asn2_traindata.csv', index_col = False)
#test_data

"""# Train Data

"""

age = train_data["Age"]
gender = train_data["Gender"]
chest_pain = train_data["Chest Pain"]
blood_pr = train_data["Blood Pr"]
cholesterol = train_data["Cholesterol"]
blood_sugar = train_data["Blood Sugar"]
num_of_vessels = train_data["# of vessels"]
defect = train_data["defect"]
y_true = train_data["Result"]

y_pred = []

for i in range(0, len(y_true)):
  
  if (age[i] >= 54):
    ans = ''
    if (gender[i] == 1):
      if (chest_pain[i] >= 2):
        if (cholesterol[i] >= 200):
          if (num_of_vessels[i] == 0):
            ans = "no"
          else:
            ans = "yes"
        else:
          ans = "no"
      elif (chest_pain[i] == 2):
        if (cholesterol[i] >= 235):
          if (num_of_vessels[i] == 0):
            ans = "no"
          else:
            ans = "yes"
        else:
          ans = "yes"
      else:
        if (cholesterol[i] >= 220):
          ans = "yes"
        else:
          ans = "no"
    else:
      if (chest_pain[i] >= 4):
        if (cholesterol[i] > 265):
          ans = "yes"
        else:
          ans = "no"
      else:
        ans = "no"
  else:
    ans = 'no'

  y_pred.append(ans)
  
  

print(len(y_pred))
y_pred,y_true

import numpy as np
count=0
for i in range(len(y_true)):
    if (y_true[i] != y_pred[i]):
        count+=1
acc=((len(y_true)-count) / len(y_true))
print("Acc = {:.2%}".format(acc))

"""# Test Data 



"""

age = test_data["Age"]
gender = test_data["Gender"]
chest_pain = test_data["Chest Pain"]
blood_pr = test_data["Blood Pr"]
cholesterol = test_data["Cholesterol"]
blood_sugar = test_data["Blood Sugar"]
num_of_vessels = test_data["# of vessels"]
defect = test_data["defect"]
y_true = test_data["Result"]

y_pred = []

for i in range(0, len(y_true)):
  
  if (age[i] >= 54):
    ans = ''
    if (gender[i] == 1):
      if (chest_pain[i] > 1):
        if (cholesterol[i] >= 200):
          if (num_of_vessels[i] == 0):
            ans = "no"
          else:
            ans = "yes"
        else:
          ans = "no"
      elif (chest_pain[i] == 2):
        if (cholesterol[i] >= 235):
          if (num_of_vessels[i] == 0):
            ans = "no"
          else:
            ans = "yes"
        else:
          ans = "yes"
      else:
        if (cholesterol[i] >= 220):
          ans = "yes"
        else:
          ans = "no"
    else:
      if (chest_pain[i] >= 4):
        if (cholesterol[i] > 265):
          ans = "yes"
        else:
          ans = "no"
      else:
        ans = "no"
  else:
    ans = 'no'

  y_pred.append(ans)
  
  

print(len(y_pred))
y_pred,y_true

import numpy as np
count=0
for i in range(len(y_true)):
    if (y_true[i] != y_pred[i]):
        count+=1
acc=((len(y_true)-count) / len(y_true))
print("Acc = {:.2%}".format(acc))

